application:
  image: tianon/true
  volumes:
    - .:/var/www/application
mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: application_user
    MYSQL_PASSWORD: application_password
    MYSQL_DATABASE: application_database
  volumes:
    - ./Docker/mysql:/docker-entrypoint-initdb.d
nginx:
  image: nginx:1.9
  dns:
    - 8.8.8.8
    - 8.8.4.4
  links:
    - php
  ports:
    - "80:80"
  volumes_from:
    - application
  volumes:
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
php:
  image: pcodk/php7
  dns:
    - 8.8.8.8
    - 8.8.4.4
  links:
    - mysql
    - mailhog
  volumes_from:
    - application
  environment:
    FLOW_CONTEXT: Development/Docker
    XDEBUG_CONFIG: remote_host=172.17.0.1
mailhog:
  image: mailhog/mailhog
  ports:
    - "8025:8025"
devtools:
  image: pcodk/devtools
  volumes_from:
    - application
  environment:
    FLOW_CONTEXT: Development/Docker
phpcs:
  image: pcodk/phpcs
  volumes_from:
    - application
  environment:
    FLOW_CONTEXT: Development/Docker
